import { NextRequest, NextResponse } from "next/server";
import { setSession, tokens } from "@/lib/server-session";
export const runtime = "nodejs";
function base() { const value = process.env.REST_OTM_API_URL; if (!value) throw new Error("REST_OTM_API_URL is not configured"); return value.replace(/\/$/, ""); }
async function upstream(req: NextRequest, accessToken: string, path: string[], body?: string) { const url = new URL(`${base()}/${path.map(encodeURIComponent).join("/")}`); url.search = req.nextUrl.search; return fetch(url, { method: req.method, headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": req.headers.get("content-type") || "application/json", ...(req.headers.get("x-tenant-id") ? { "x-tenant-id": req.headers.get("x-tenant-id")! } : {}) }, body: body || undefined }); }
async function handler(req: NextRequest, context: { params: Promise<{ path: string[] }> }) { try { const { path } = await context.params; const current = tokens(req); if (!current.accessToken) return NextResponse.json({ message: "Oturum gerekli." }, { status: 401 }); const body = req.method === "GET" || req.method === "HEAD" ? undefined : await req.text(); let result = await upstream(req, current.accessToken, path, body); let refreshed: { accessToken: string; refreshToken: string } | null = null; if (result.status === 401 && current.refreshToken) { const refresh = await fetch(`${base()}/auth/refresh`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ refreshToken: current.refreshToken }) }); if (refresh.ok) { const json = await refresh.json(); const nextTokens = json.data as { accessToken?: string; refreshToken?: string }; if (nextTokens.accessToken && nextTokens.refreshToken) { refreshed = { accessToken: nextTokens.accessToken, refreshToken: nextTokens.refreshToken }; result = await upstream(req, refreshed.accessToken, path, body); } } }
  const response = new NextResponse(result.body, { status: result.status, headers: { "Content-Type": result.headers.get("content-type") || "application/json", "Cache-Control": "no-store" } }); if (refreshed?.accessToken && refreshed.refreshToken) setSession(response, refreshed); return response;
 } catch (error) { console.error("[superadmin-bff]", error); return NextResponse.json({ message: "Yönetim API bağlantısı kurulamadı." }, { status: 502 }); } }
export const GET = handler; export const POST = handler; export const PATCH = handler; export const PUT = handler; export const DELETE = handler;
